const DecksActionTypes = {
    FETCH_DECKS_START: 'FETCH_DECKS_START',
    FETCH_DECKS_SUCCESS: 'FETCH_DECKS_SUCCESS',
    FETCH_DECKS_FAILED: 'FETCH_DECKS_FAILED',
    SET_SPECIFIC_DECK: 'SET_SPECIFIC_DECK',
    ADD_DECK: 'ADD_DECK',
    DELETE_DECK: 'DELETE_DECK',
    EDIT_DECK: 'EDIT_DECK',
}

export default DecksActionTypes;
