const DecksActionTypes = {
    SET_SPECIFIC_DECK_ID: 'SET_SPECIFIC_DECK_ID',
    SET_DECK_LIST: 'SET_DECK_LIST',
    EDIT_DECK: 'EDIT_DECK',
    DELETE_DECK: 'DELETE_DECK',
    ADD_DECK: 'ADD_DECK',
    SET_FLASHCARD_LIST: 'SET_FLASHCARD_LIST',
    ADD_FLASHCARD: 'ADD_FLASHCARD',
    DELETE_FLASHCARD: 'DELETE_FLASHCARD',
}

export default DecksActionTypes;
