const ModalsActionTypes = {
    TOGGLE_DECK_MODAL: 'TOGGLE_DECK_MODAL',
    TOGGLE_FLASHCARD_MODAL: 'TOGGLE_FLASHCARD_MODAL',
    TOGGLE_DELETE_DECK_MODAL: 'TOGGLE_DELETE_DECK_MODAL',
    TOGGLE_ERROR_MODAL: 'TOGGLE_ERROR_MODAL',
}

export default ModalsActionTypes;
